### ISSUE TITLE
Use of uninitialized value in numeric gt (>) at /usr/bin/pgcluu line 6646.

### ISSUE THREAD

**Issue by madtibo** [darold/pgcluu#109]
Salut Gilles,

A client got the following error using version 2.9 :
```
$ pgcluu -o rapport24h/ pgcluu_collect/
Use of uninitialized value in numeric gt (>) at /usr/bin/pgcluu line 6646.
```

l.6646: `$OVERALL_STATS{'database'}{$db}{'size'} > $overall_stat_databases{'size'}[1]`

I do not have his data so I cannot run the report again to debug further.

Cordialement,

**Comment by darold** [comment]
Hi,

Unfortunately pgCluu doesn't maintain different branches for some versions, that mean that it is mandatory to upgrade to latest version before reporting a bug as this is the first thing I will ask. When there is lot of change since last release I can also ask to upgrade to latest development code.

Best regards

**Comment by madtibo** [comment]
The client did not keep collectd data. So no way to test on last version.
I will therefore close this ticket.
Thanks for the quick answer et bonne semaine !
