### ISSUE TITLE
Prompt for Password

### ISSUE THREAD

**Issue by bhaktirajdev** [darold/pgcluu#41]
Hello,

Hi,
I installed and used the pgCluu as following:
tar xzf pgcluu-2.x.tar.gz
cd pgcluu-2.x/
perl Makefile.PL
make && sudo make install
mkdir /tmp/stat_db1/
pgcluu_collectd -D -i 60 /tmp/stat_db1/ -d dbname
then came:
pgxl@localhost-> LOG: Detach from terminal with pid: 23754

after a while I tried the command:
pgcluu_collectd -k
then came the error:
ERROR: can't find /tmp/pgcluu_collectd.pid, is pgcluu_collectd running?
Also, there was nothing in the /tmp/stat_db1 except the sysinfo.txt

When i run it without -D then it shows the message pg_cluu started but asks me postgres password many times. I entered the password 5 times and then terminated it.Now the data is present in the stat_db1 folder.

But with -D option I am not able to get the statistics.

Is there any option to provide password in command line itself that I am missing?
I read the command line options, but did not find any. 

What am i missing?

**Comment by darold** [comment]
Hi,

If you can't allow pgcluu_collectd to connect without password then you can set a .pgpass file because pgcluu_collectd is using psql to query your database.You can also set the PGPASSWORD environment variable or if you don't care that your password appears in command line, using -W or --password option might help.

Please use latest developement code I've just commit some fix about that.

Regards,

**Comment by bhaktirajdev** [comment]
Ok.
Thanks a lot! :)
