### ISSUE TITLE
pgcluu_collected Report  show  disable bufferCache Statistics 

### ISSUE THREAD

**Issue by rmijangos** [darold/pgcluu#72]
I generated report with pgcluu,  when i open the html result,   the bufferCache Statistics is disabled on menu,   do you have any idea?   

Collect Data with follow line command 

pgcluu_collectd -D -i 60 /tmp/stat_db1/ -h inst-rds-dev.xxxxxxxxxxx.us-east-1.rds.amazonaws.com -U user -d pp_dev --pgbouncer-args='-p 5342'

Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 5206.
Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 5206.
Use of uninitialized value in addition (+) at /usr/local/bin/pgcluu line 5206.
Argument "-" isn't numeric in numeric ge (>=) at /usr/local/bin/pgcluu line 5131.

Create report 
pgcluu -o /tmp/report_db1/ /tmp/stat_db1/

**Comment by darold** [comment]
To obtain report about bufferCache Statistics you need to enable it in the statistics collector. This can be achieved by using `-B` or `--enable-buffercache` in your pgcluu_collectd command. This is not enabled by default because it uses some additional resources that must be followed on a production server. 

Also please use latest development code, this might solves the error with uninitialized value. I will try to publish version 2.5 this weekend.
