### ISSUE TITLE
Monthly / Single Report out of daily rotated logs

### ISSUE THREAD

**Issue by Markus-** [darold/pgcluu#79]
I collect the data with
./pgcluu_collectd -D -i 60 -r -z /performance/

so there are output directories like /performance/2016/12/<01|02|03...>.

Is there any option in pgcluu to build a report for the whole month (or a report which includes all data in /performance)?

**Comment by darold** [comment]
Hi

You can not build a static report for a week/month/year, pgcluu can only be used to build daily dedicated report. 

If you want this feature, there is a CGI script cgi-bin/pgcluu.cgi that can be used to dynamically generate reports. This is still a work in progress, there is no documentation but it works pretty well. You just have to install the content of the cgi-bin/ directory into a CGI enabled directory and configure file pgcluu.conf.

Before using the CGI you have to execute pgcluu in cache mode (option -C) periodically to generate cache file, otherwise loading data from cgi is too slow. The data directory can be permanently extended by pgcluu_collectd.

Give it a try and let me know if you have any issue.

**Comment by Markus-** [comment]
I think I'll go with daily reports and just create an overview page.
Not sure if cgi is allowed on the given system (security department).

Thanks.
